### PR TITLE
feat: enable public ip and authorized external networks

### PR DESCRIPTION
**Pull request by bruno561**
#81

### CODE REVIEW

**Comment by bruno561** [comment]
@anaik91 and @imrannayer review, pls?

**Comment by imrannayer** [comment]
@bruno561 thanks for the PR. Can you plz follow [this doc](https://github.com/GoogleCloudPlatform/terraform-google-alloy-db/blob/main/CONTRIBUTING.md) to fix lint issues.

**Comment by bruno561** [comment]
@imrannayer You're welcome.
Done!

**Review by imrannayer — APPROVED** [review]

**Pull request merged**
